# Using `kugupu` to calculate molecular coupling networks

This notebook demonstrates how to calculate molecular coupling between fragments, inspect the results and save and load these results to file.  These results files will be the basis of all further analysis done using the `kugupu` package.

This will require version 0.20.0 of MDAnalysis, and kugupu to be installed.

In [1]:
import MDAnalysis as mda
import kugupu as kgp

models available
{'ocelotml': <class 'kugupu.ocelotl_model.OcelotMLModel'>, 'yaehmop': <class 'kugupu.yaehmop.YaehmopModel'>}


Firstly we create an `MDAnalysis.Universe` object from our simulation files:

In [2]:
u = mda.Universe('datafiles/C6.data', 'datafiles/C6.dcd')

/Users/k2584788/.local/share/mamba/envs/forked_kugupu/lib/python3.10/site-packages/MDAnalysis/coordinates/DCD.py:165: DeprecationWarning: DCDReader currently makes independent timesteps by copying self.ts while other readers update self.ts inplace. This behavior will be changed in 3.0 to be the same as other readers. Read more at https://github.com/MDAnalysis/mdanalysis/issues/3889 to learn if this change in behavior might affect you.
  warnings.warn("DCDReader currently makes independent timesteps"


This system has 46,500 atoms in 250 different fragments.

In [3]:
print(u.atoms.n_atoms, len(u.atoms.fragments))

46500 250


Our dynamics simulation has 5 frames of results.

In [4]:
print(u.trajectory.n_frames)

5


To perform the coupling calculations our `Universe` will require bond information (for determining fragments) and element information (for the tight binding calculations) stored inside the `.names` attribute.

Our Lammps Data file did not include element symbols, so we can add these to the Universe now...

In [5]:
def add_names(u):
    # Guesses atom names based upon masses
    def approx_equal(x, y):
        return abs(x - y) < 0.1
    
    # mapping of atom mass to element
    massdict = {}
    for m in set(u.atoms.masses):
        for elem, elem_mass in mda.guesser.tables.masses.items():
            if approx_equal(m, elem_mass):
                massdict[m] = elem
                break
        else:
            raise ValueError
            
    u.add_TopologyAttr('names')
    for m, e in massdict.items():
        u.atoms[u.atoms.masses == m].names = e

add_names(u)

## Running the coupling matrix calculation

The coupling matrix between fragments is calculated using the `kgp.coupling_matrix` function.

Here we are calculating the coupling matrix for fragments in the Universe `u` where
- coupling is calculated between fragments with a closest approach of less than 5.0 Angstrom (`nn_cutoff`)
- coupling is calculated between the LUMO upwards (`state='lumo'`)
- one state per fragment is considered (`degeneracy=1`)
- we will analyse up to frame 3 (`stop=3`)

This function will (for each frame)
- identify which fragments are close enough to possibly be electronically coupled
- run a tight binding calculation between all pairs identified
- calculate the molecular coupling based on this tight binding calculation

In [6]:
res = kgp.coupling_matrix(u, nn_cutoff=5.0, state='lumo', degeneracy=1, stop=3)

2025-06-17T14:14:16.265170+0100 INFO Processing 3 frames
2025-06-17T14:14:16.268688+0100 INFO Processing frame 1 of 3
2025-06-17T14:14:16.366599+0100 INFO Finding dimers within 5.0, passed 250 fragments
2025-06-17T14:14:16.845472+0100 INFO Found 3282 dimers
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....


no shift
Hii is [[-2.14000000e+01 -0.00000000e+00 -0.00000000e+00 ... -2.86431388e-06
  -1.30869185e-05 -1.01392083e-05]
 [-0.00000000e+00 -1.14000000e+01 -0.00000000e+00 ...  1.21741386e-06
   3.48512307e-06  5.00767256e-06]
 [-0.00000000e+00 -0.00000000e+00 -1.14000000e+01 ...  2.19435160e-06
   1.16780105e-05  8.56680811e-06]
 ...
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -1.36000000e+01
  -3.31241261e+00 -4.01394025e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -1.36000000e+01 -3.13330324e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -0.00000000e+00 -1.36000000e+01]]
Hij is [[-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 ...
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]]
v is [[-1.53085762e-04]
 [-2.23731259e-03]
 [-1.75857389e-03]
 [-3.81041088e-03]
 [ 1.82612719e-04]
 [-6.67628557e-03]
 [-1.00298461e-02]
 [-1.016570

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....


no shift
Hii is [[-2.14000000e+01 -0.00000000e+00 -0.00000000e+00 ... -2.86431388e-06
  -1.30869185e-05 -1.01392083e-05]
 [-0.00000000e+00 -1.14000000e+01 -0.00000000e+00 ...  1.21741386e-06
   3.48512307e-06  5.00767256e-06]
 [-0.00000000e+00 -0.00000000e+00 -1.14000000e+01 ...  2.19435160e-06
   1.16780105e-05  8.56680811e-06]
 ...
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -1.36000000e+01
  -3.31241261e+00 -4.01394025e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -1.36000000e+01 -3.13330324e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -0.00000000e+00 -1.36000000e+01]]
Hij is [[-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -0.00000000e+00 -0.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -0.00000000e+00 -0.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -0.00000000e+00 -0.00000000e+00]
 ...
 [-0.00000000e+00 -0.

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....


v is [[-1.47223425e-04]
 [ 8.65521721e-03]
 [ 3.31698486e-03]
 [-1.72612086e-03]
 [ 6.23294925e-05]
 [-8.36395672e-04]
 [-5.29072294e-04]
 [ 7.03263726e-05]
 [ 5.51843885e-04]
 [-9.53954804e-03]
 [-3.48545715e-03]
 [ 1.97149798e-03]
 [-2.09028005e-04]
 [ 2.38143493e-03]
 [ 6.60791279e-04]
 [-8.18622995e-04]
 [ 5.46363769e-04]
 [ 7.89774431e-03]
 [ 3.90369347e-03]
 [-8.79849790e-04]
 [ 1.64767281e-05]
 [-1.21064955e-03]
 [-3.69152396e-04]
 [ 1.72518393e-05]
 [ 3.16456905e-05]
 [ 2.60004945e-06]
 [-3.45059837e-05]
 [-1.11046705e-03]
 [-2.84964072e-04]
 [ 2.51560791e-04]
 [ 8.39122373e-05]
 [ 6.52324958e-03]
 [ 2.62098463e-03]
 [-1.74474718e-03]
 [-1.28414566e-04]
 [-1.80062618e-04]
 [-1.17845355e-04]
 [-2.82447569e-04]
 [-1.55215120e-05]
 [ 6.81775229e-04]
 [ 5.63940101e-04]
 [ 3.45310586e-05]
 [-2.89058711e-05]
 [-1.94059024e-03]
 [-6.77120990e-04]
 [-2.11244379e-04]
 [-9.41231130e-05]
 [ 4.09377271e-03]
 [ 1.90086237e-03]
 [-3.39587975e-04]
 [-8.02799184e-05]
 [-4.88623176e-04]
 [-7.87

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....


for j bit the H_frag insert is [-10.42728372]
no shift
Hii is [[-2.14000000e+01 -0.00000000e+00 -0.00000000e+00 ... -2.86431388e-06
  -1.30869185e-05 -1.01392083e-05]
 [-0.00000000e+00 -1.14000000e+01 -0.00000000e+00 ...  1.21741386e-06
   3.48512307e-06  5.00767256e-06]
 [-0.00000000e+00 -0.00000000e+00 -1.14000000e+01 ...  2.19435160e-06
   1.16780105e-05  8.56680811e-06]
 ...
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -1.36000000e+01
  -3.31241261e+00 -4.01394025e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -1.36000000e+01 -3.13330324e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -0.00000000e+00 -1.36000000e+01]]
Hij is [[-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 ...
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]]
v is [[ 2.85492495e-04]
 [-9.91079417e-04]
 [-7.16882168e-03]
 [-3.09360961e-03]
 [ 1.27700085e-05]
 [ 

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 368 and 365 (0.991499 A) is suspicious.


shift
Hii is [[-2.14000000e+01 -0.00000000e+00 -0.00000000e+00 ... -2.86431388e-06
  -1.30869185e-05 -1.01392083e-05]
 [-0.00000000e+00 -1.14000000e+01 -0.00000000e+00 ...  1.21741386e-06
   3.48512307e-06  5.00767256e-06]
 [-0.00000000e+00 -0.00000000e+00 -1.14000000e+01 ...  2.19435160e-06
   1.16780105e-05  8.56680811e-06]
 ...
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -1.36000000e+01
  -3.31241261e+00 -4.01394025e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -1.36000000e+01 -3.13330324e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -0.00000000e+00 -1.36000000e+01]]
Hij is [[-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 ...
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]]
v is [[-8.16254834e-04]
 [ 7.83071171e-03]
 [-3.74344984e-03]
 [-1.94416205e-02]
 [ 3.18148605e-04]
 [-1.19608830e-03]
 [ 9.93475291e-04]
 [ 3.32836417e

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 235 and 215 (0.997515 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 370 and 369 (0.995440 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 295 and 290 (0.982551 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using defau

v is [[ 3.37718732e-04]
 [ 6.62403127e-04]
 [-4.95871291e-03]
 [ 2.02996561e-03]
 [-2.91765516e-04]
 [ 5.08167099e-03]
 [-2.09466458e-02]
 [ 2.49370143e-03]
 [ 5.57408854e-04]
 [ 1.28645677e-03]
 [ 2.22168115e-03]
 [-1.77113463e-03]
 [ 2.59286625e-04]
 [ 4.28125129e-03]
 [-2.53726441e-02]
 [ 9.00223352e-03]
 [ 6.08184565e-05]
 [-2.08998760e-04]
 [ 4.05599721e-03]
 [-1.43415440e-03]
 [ 8.19619033e-04]
 [-2.20391701e-03]
 [ 2.38371595e-02]
 [-8.58532227e-03]
 [-1.87206722e-04]
 [-6.42552086e-04]
 [ 4.84693648e-05]
 [-1.24798683e-03]
 [ 3.83067208e-03]
 [-3.10600268e-04]
 [-1.22759034e-03]
 [ 3.20537084e-05]
 [-7.36473931e-03]
 [ 4.06045114e-04]
 [-2.74261098e-03]
 [-9.50797184e-03]
 [ 5.17838912e-02]
 [-6.17128864e-03]
 [ 9.63270124e-04]
 [ 6.87650635e-03]
 [-5.05896758e-02]
 [ 8.39261398e-03]
 [ 8.66901181e-04]
 [ 1.06962346e-02]
 [-5.10033029e-02]
 [ 9.75457828e-03]
 [-5.07112953e-04]
 [-1.82168938e-03]
 [ 1.62540890e-03]
 [-5.82738924e-03]
 [ 1.26478984e-04]
 [ 1.97646624e-04]
 [ 1.97

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 337 and 336 (0.999668 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using defau

v is [[-1.42684834e-04]
 [-1.77706451e-03]
 [ 1.06921449e-02]
 [-4.78580054e-03]
 [ 1.28714881e-04]
 [ 5.38768318e-04]
 [-3.26439229e-03]
 [ 1.97598945e-03]
 [-1.99439355e-04]
 [ 2.21151687e-03]
 [-9.16764106e-03]
 [ 5.96819005e-03]
 [ 3.30479690e-04]
 [-9.68447157e-04]
 [ 1.36393109e-03]
 [-4.83704386e-04]
 [-5.99206297e-04]
 [-9.89375761e-04]
 [ 8.90962886e-03]
 [-5.90227533e-03]
 [ 2.83374085e-04]
 [-1.24683619e-03]
 [ 3.67980392e-04]
 [ 9.63225394e-04]
 [-2.77268904e-04]
 [-1.53655788e-04]
 [-5.33876983e-05]
 [ 8.03946958e-04]
 [-4.95314416e-04]
 [ 3.06020570e-04]
 [ 1.54265246e-04]
 [-2.62877736e-03]
 [ 6.95410071e-03]
 [-4.21274838e-03]
 [-1.20659903e-05]
 [-6.79209515e-04]
 [ 2.13200960e-03]
 [-1.31407904e-03]
 [-1.71456467e-04]
 [ 6.48369714e-04]
 [-1.52593104e-03]
 [ 8.31493595e-04]
 [ 2.48704399e-05]
 [ 3.56559096e-04]
 [-3.12773310e-03]
 [ 2.71664283e-03]
 [ 1.34733768e-04]
 [-2.08339147e-04]
 [ 2.46749011e-03]
 [-1.36681786e-03]
 [-6.23723914e-05]
 [-1.04182592e-03]
 [-3.78

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 304 and 303 (

Hii is [[-2.14000000e+01 -0.00000000e+00 -0.00000000e+00 ... -2.86431388e-06
  -1.30869185e-05 -1.01392083e-05]
 [-0.00000000e+00 -1.14000000e+01 -0.00000000e+00 ...  1.21741386e-06
   3.48512307e-06  5.00767256e-06]
 [-0.00000000e+00 -0.00000000e+00 -1.14000000e+01 ...  2.19435160e-06
   1.16780105e-05  8.56680811e-06]
 ...
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -1.36000000e+01
  -3.31241261e+00 -4.01394025e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -1.36000000e+01 -3.13330324e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -0.00000000e+00 -1.36000000e+01]]
Hij is [[-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 ...
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]]
v is [[ 7.35776751e-04]
 [ 7.69261746e-03]
 [ 3.28073589e-02]
 [ 2.01711779e-02]
 [-5.12550808e-04]
 [-2.60326319e-04]
 [-1.08758421e-03]
 [-1.22522942e-03]
 

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 261 and 258 (0.998742 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using defau

v is [[-9.87841510e-05]
 [-5.97792106e-05]
 [ 5.43209045e-04]
 [-7.66755515e-04]
 [ 4.71082501e-05]
 [-2.23799375e-03]
 [ 1.57501142e-03]
 [-6.28887071e-03]
 [-7.43052413e-05]
 [ 8.63457975e-05]
 [ 9.07512962e-04]
 [-8.82516229e-05]
 [-2.41758168e-06]
 [-2.26982844e-03]
 [ 1.37527416e-03]
 [-6.05254340e-03]
 [-1.33016674e-04]
 [ 5.02318931e-04]
 [-9.98339865e-05]
 [ 1.49326305e-03]
 [ 2.80409891e-05]
 [ 2.10152123e-03]
 [-3.26796837e-03]
 [ 6.33797912e-03]
 [ 3.60258989e-04]
 [ 2.94268264e-04]
 [-6.20988497e-05]
 [ 8.22094093e-04]
 [ 2.43254908e-04]
 [ 1.20044697e-03]
 [ 2.12347327e-04]
 [-1.58670017e-03]
 [-1.04892531e-04]
 [-2.15021927e-03]
 [ 5.71513290e-04]
 [ 2.85736169e-03]
 [-6.34453329e-03]
 [ 1.26293514e-02]
 [ 4.50573054e-05]
 [-5.15364807e-03]
 [ 7.92053971e-03]
 [-1.26692834e-02]
 [-4.94903964e-04]
 [-3.74313832e-03]
 [ 3.13177436e-03]
 [-1.24831517e-02]
 [-5.64062980e-04]
 [ 1.04355566e-03]
 [-8.17148430e-04]
 [ 3.42670072e-03]
 [ 5.57232650e-05]
 [ 2.72726710e-04]
 [-2.69

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 293 and 289 (0.994647 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using defau

v is [[-9.22306745e-06]
 [-4.28176467e-04]
 [ 3.30747430e-04]
 [ 7.74446807e-05]
 [-9.90822921e-06]
 [ 1.01567951e-04]
 [-5.70036873e-05]
 [-5.91742685e-05]
 [ 3.15516662e-06]
 [ 4.01154436e-04]
 [-4.51406281e-04]
 [-1.16000075e-04]
 [-3.90791197e-05]
 [ 3.01045615e-05]
 [ 1.51621255e-04]
 [-3.06399708e-05]
 [ 4.27695704e-05]
 [-5.36028914e-04]
 [ 1.99538434e-04]
 [ 1.68356919e-04]
 [-4.31290396e-06]
 [ 7.02153327e-05]
 [ 1.04878218e-04]
 [-1.40245329e-04]
 [ 4.97426404e-05]
 [ 3.27362321e-05]
 [ 5.21324793e-06]
 [ 1.87679470e-05]
 [-5.06124692e-05]
 [-3.26959182e-05]
 [ 3.19589008e-06]
 [-3.70457576e-04]
 [ 3.28425271e-04]
 [ 7.36234238e-05]
 [-1.15370417e-05]
 [-2.68530060e-05]
 [ 9.84239318e-05]
 [ 7.09060647e-06]
 [ 2.41219343e-06]
 [ 3.81434834e-05]
 [-2.89962423e-05]
 [-5.73949968e-06]
 [ 2.32582334e-06]
 [ 1.28984257e-04]
 [-6.20609039e-05]
 [-2.67949073e-05]
 [-5.31017442e-06]
 [-9.35111278e-05]
 [ 3.83144027e-05]
 [ 6.34743264e-06]
 [-4.58282803e-05]
 [ 4.35252807e-05]
 [ 3.22

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 360 and 357 (0.991002 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using defau

Hii is [[-21.4         -0.          -0.         ...  -0.          -0.
   -0.        ]
 [ -0.         -11.4         -0.         ...  -0.          -0.
   -0.        ]
 [ -0.          -0.         -11.4        ...  -0.          -0.
   -0.        ]
 ...
 [ -0.          -0.          -0.         ... -13.6         -3.34993933
   -3.7501314 ]
 [ -0.          -0.          -0.         ...  -0.         -13.6
   -3.78747199]
 [ -0.          -0.          -0.         ...  -0.          -0.
  -13.6       ]]
Hij is [[-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 ...
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]]
v is [[-2.36551630e-04]
 [ 2.91562701e-03]
 [-1.41093546e-04]
 [ 4.34868347e-04]
 [ 7.41470864e-04]
 [ 1.13713694e-02]
 [-1.05664686e-02]
 [ 1.12936983e-03]
 [ 2.95552947e-05]
 [ 1.54540811e-03]
 [-5.02328169e-04]
 [ 1.68641759e-03]
 [ 4.82867473e-04]
 [ 1.34271195e-02]
 [-8.59043799e-03]
 [ 8.17720206e-

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 308 and 306 (0.997594 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using defau

Hii is [[-21.4         -0.          -0.         ...  -0.          -0.
   -0.        ]
 [ -0.         -11.4         -0.         ...  -0.          -0.
   -0.        ]
 [ -0.          -0.         -11.4        ...  -0.          -0.
   -0.        ]
 ...
 [ -0.          -0.          -0.         ... -13.6         -3.34993933
   -3.7501314 ]
 [ -0.          -0.          -0.         ...  -0.         -13.6
   -3.78747199]
 [ -0.          -0.          -0.         ...  -0.          -0.
  -13.6       ]]
Hij is [[-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 ...
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]]
v is [[ 8.85013954e-04]
 [-1.82687491e-02]
 [-1.79612179e-02]
 [-1.03117119e-02]
 [-2.47607377e-04]
 [ 2.31174613e-03]
 [ 2.34621891e-03]
 [ 1.36555549e-03]
 [ 1.99995156e-05]
 [ 1.75313980e-02]
 [ 1.97534922e-02]
 [ 1.18128823e-02]
 [ 2.46593113e-04]
 [-3.41391202e-03]
 [-3.93088451e-03]
 [-1.63383498e-

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 235 and 215 (

v is [[ 4.52428086e-04]
 [ 2.21033531e-03]
 [-7.73270540e-03]
 [-1.47992560e-03]
 [-8.21860839e-04]
 [ 1.12123598e-02]
 [-2.29201104e-02]
 [ 5.69057525e-04]
 [ 1.46076619e-04]
 [-2.08029696e-03]
 [ 2.30712507e-03]
 [-2.29155393e-03]
 [ 1.26878906e-03]
 [ 1.28576570e-02]
 [-2.96045398e-02]
 [-4.42251061e-03]
 [ 2.51125301e-04]
 [-1.82814214e-03]
 [ 6.29243863e-03]
 [ 2.01870929e-04]
 [ 3.29384594e-04]
 [-1.11301951e-02]
 [ 2.96473778e-02]
 [ 1.61953668e-03]
 [-4.98021036e-04]
 [-1.11557849e-03]
 [-1.27589996e-04]
 [-2.52438015e-03]
 [ 1.46062284e-03]
 [-6.15532295e-04]
 [-1.61449456e-03]
 [-2.52907436e-03]
 [ 1.12470943e-02]
 [ 1.59745008e-03]
 [-2.79445302e-04]
 [-2.22839645e-02]
 [ 5.40374359e-02]
 [ 1.14105451e-02]
 [ 7.90108223e-04]
 [ 2.11069255e-02]
 [-4.64545663e-02]
 [-9.73336545e-03]
 [-1.68243102e-04]
 [ 2.15493822e-02]
 [-4.01028519e-02]
 [-3.57947244e-03]
 [ 1.60949392e-03]
 [ 4.62957074e-03]
 [-2.77226718e-02]
 [-5.83193420e-03]
 [-9.55552926e-05]
 [-1.04054653e-04]
 [ 1.83

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 370 and 369 (0.995440 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using defau

v is [[-4.18338091e-05]
 [-3.55164622e-04]
 [-2.23366792e-04]
 [-3.68344799e-04]
 [ 1.30913457e-04]
 [-5.22330086e-03]
 [-1.63708049e-03]
 [-2.07881115e-03]
 [ 6.62784445e-05]
 [-3.28209932e-04]
 [-6.43069625e-05]
 [-1.62000141e-04]
 [ 5.65057249e-06]
 [-4.42617668e-03]
 [-1.72772850e-03]
 [-2.85673440e-03]
 [ 7.27474095e-05]
 [ 1.36048287e-03]
 [ 4.99384895e-04]
 [ 9.26549665e-04]
 [ 8.40258810e-05]
 [ 4.71996451e-03]
 [ 2.57586823e-03]
 [ 1.63559553e-03]
 [-2.22159202e-04]
 [-6.18216970e-05]
 [-1.77167238e-04]
 [ 6.25775899e-04]
 [ 6.61252119e-06]
 [-6.22674162e-04]
 [ 3.41938724e-04]
 [ 2.18361454e-03]
 [ 1.90541270e-03]
 [ 3.20805472e-03]
 [ 2.52188063e-04]
 [ 9.13664417e-03]
 [ 3.64374039e-03]
 [ 4.45243943e-03]
 [ 4.74148563e-05]
 [-6.13867609e-03]
 [-4.49160129e-03]
 [-6.01952732e-03]
 [ 6.73532338e-04]
 [-8.58578310e-03]
 [-4.74838613e-03]
 [-7.65670948e-04]
 [-4.62526289e-04]
 [-3.84435108e-03]
 [-3.09989314e-03]
 [-2.74801598e-03]
 [-3.56170743e-06]
 [ 4.52669949e-04]
 [ 3.13

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/mini

v is [[ 3.65239024e-04]
 [ 1.12026237e-03]
 [ 1.20100164e-02]
 [-4.36747324e-03]
 [-9.66480815e-05]
 [-5.38943673e-04]
 [-3.16968828e-03]
 [ 8.11640700e-04]
 [-1.77839085e-04]
 [-6.24618666e-04]
 [-1.25881982e-02]
 [ 5.31328199e-03]
 [-1.68850637e-04]
 [-1.56421235e-04]
 [ 9.01826361e-04]
 [-2.88344393e-04]
 [ 4.54891184e-04]
 [ 3.43178562e-05]
 [ 1.13372283e-02]
 [-4.18837891e-03]
 [ 3.87886452e-05]
 [-5.17625883e-04]
 [ 4.72770898e-04]
 [ 4.64241363e-05]
 [ 1.00860018e-04]
 [-3.46668584e-05]
 [-8.14143966e-05]
 [ 7.44957322e-05]
 [-1.00228072e-03]
 [ 4.06224821e-04]
 [ 4.77572452e-05]
 [ 9.29792053e-04]
 [ 1.05872985e-02]
 [-2.75354074e-03]
 [ 1.31992266e-04]
 [ 7.95910964e-05]
 [ 2.99362197e-03]
 [-1.21242231e-03]
 [ 9.78430044e-05]
 [-1.15379976e-04]
 [-2.38779620e-03]
 [ 5.19393547e-04]
 [ 1.30627341e-04]
 [-1.34242291e-03]
 [-4.19399599e-03]
 [ 2.11830626e-03]
 [-1.85671657e-04]
 [ 4.15971308e-04]
 [ 1.79949338e-03]
 [-1.47140884e-03]
 [ 8.47470450e-06]
 [-1.33418796e-03]
 [-2.83

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 157 and 156 (0.982676 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 157 and 156 (0.982676 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 157 and 156 (0.982676 A) is suspicious.
!!! Warning !!! Distance between atoms 256 and 236 (0.994447 A) is suspicious.
!!! Warning !!! Distance between atoms 311 and 309 (0.997406 A) is suspicious.


no shift
Hii is [[-21.4         -0.          -0.         ...  -0.          -0.
   -0.        ]
 [ -0.         -11.4         -0.         ...  -0.          -0.
   -0.        ]
 [ -0.          -0.         -11.4        ...  -0.          -0.
   -0.        ]
 ...
 [ -0.          -0.          -0.         ... -13.6         -3.67434047
   -4.06486313]
 [ -0.          -0.          -0.         ...  -0.         -13.6
   -2.87869856]
 [ -0.          -0.          -0.         ...  -0.          -0.
  -13.6       ]]
Hij is [[-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 ...
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]]
v is [[ 7.99225103e-05]
 [-1.32683160e-03]
 [ 4.06467248e-03]
 [ 4.12349554e-03]
 [-4.82254721e-05]
 [ 2.39573679e-04]
 [-5.66171706e-04]
 [-4.30120285e-04]
 [-1.67321558e-04]
 [-9.54696422e-04]
 [-3.56868973e-03]
 [-4.64949648e-03]
 [ 5.52834677e-05]
 [-9.18538386e-05]
 [ 8.87021984e-04]
 [ 1.0

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 157 and 156 (0.982676 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 157 and 156 (0.982676 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 157 and 156 (0.982676 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 157 and 156 (0.982676 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/mini

v is [[-2.06257543e-05]
 [ 2.02156240e-04]
 [-3.10587297e-04]
 [ 1.19974911e-04]
 [ 5.20614949e-06]
 [-9.26852915e-05]
 [ 1.24189279e-04]
 [-5.24843297e-05]
 [-1.21096283e-06]
 [-2.37557449e-04]
 [ 2.61499000e-04]
 [-1.04006795e-04]
 [-8.95530247e-06]
 [ 8.33163490e-05]
 [-1.02677972e-04]
 [ 5.16473224e-05]
 [ 7.35805442e-06]
 [ 2.02151707e-04]
 [-2.52891211e-04]
 [ 8.42782578e-05]
 [ 2.69810651e-05]
 [ 7.13158025e-05]
 [-3.88674030e-05]
 [-9.76503373e-06]
 [ 1.18859476e-05]
 [ 9.80903869e-06]
 [-5.33029048e-06]
 [-2.43336651e-05]
 [ 1.43678797e-06]
 [ 1.00874017e-05]
 [-3.63029955e-06]
 [ 1.67695134e-04]
 [-1.73471204e-04]
 [ 6.12227960e-05]
 [ 2.44737631e-07]
 [ 2.31913913e-05]
 [-3.35829646e-05]
 [ 1.21120213e-05]
 [-5.36099703e-06]
 [-1.82405608e-05]
 [ 2.73922547e-05]
 [-4.44223971e-06]
 [-6.25051216e-06]
 [-5.90702516e-05]
 [ 6.70566947e-05]
 [-4.72262517e-05]
 [ 1.31262329e-06]
 [ 8.96703022e-05]
 [-9.72008611e-05]
 [ 6.05203127e-05]
 [-3.42922793e-05]
 [-2.31899081e-04]
 [ 2.57

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 157 and 156 (0.982676 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 157 and 156 (0.982676 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 157 and 156 (0.982676 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 157 and 156 (0.982676 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/mini

Hii is [[-21.4         -0.          -0.         ...  -0.          -0.
   -0.        ]
 [ -0.         -11.4         -0.         ...  -0.          -0.
   -0.        ]
 [ -0.          -0.         -11.4        ...  -0.          -0.
   -0.        ]
 ...
 [ -0.          -0.          -0.         ... -13.6         -3.67434047
   -4.06486313]
 [ -0.          -0.          -0.         ...  -0.         -13.6
   -2.87869856]
 [ -0.          -0.          -0.         ...  -0.          -0.
  -13.6       ]]
Hij is [[-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 ...
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]
 [-0. -0. -0. ... -0. -0. -0.]]
no shift
Hii is [[-21.4         -0.          -0.         ...  -0.          -0.
   -0.        ]
 [ -0.         -11.4         -0.         ...  -0.          -0.
   -0.        ]
 [ -0.          -0.         -11.4        ...  -0.          -0.
   -0.        ]
 ...
 [ -0.          -0.          -0.         ... -1

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 157 and 156 (0.982676 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 157 and 156 (0.982676 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 157 and 156 (0.982676 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
!!! Warning !!! Distance between atoms 157 and 156 (0.982676 A) is suspicious.
ERROR: Can't open parameter file: /Users/runner/mini

v is [[ 1.34939589e-04]
 [-4.75255290e-04]
 [ 3.18050573e-03]
 [ 3.75883702e-03]
 [-4.18058531e-05]
 [-3.38416251e-05]
 [-4.17336983e-04]
 [-4.61072658e-04]
 [-1.65564217e-04]
 [ 4.96109452e-04]
 [-2.71099699e-03]
 [-3.85957189e-03]
 [-4.49497834e-06]
 [-1.19957585e-04]
 [ 7.64736095e-04]
 [ 1.00280353e-03]
 [ 1.12391263e-04]
 [-8.08944333e-04]
 [ 2.26492358e-03]
 [ 3.24194413e-03]
 [-1.33291531e-04]
 [ 2.09787439e-04]
 [-2.27239806e-04]
 [-7.58959811e-04]
 [-4.36091171e-05]
 [-2.81328158e-06]
 [-3.70535599e-06]
 [ 1.78216712e-04]
 [-3.42084397e-04]
 [-3.83516172e-04]
 [-4.11136618e-05]
 [-1.04422864e-03]
 [ 1.83228810e-03]
 [ 2.69400950e-03]
 [ 6.79360812e-05]
 [ 1.68922409e-04]
 [-1.94558374e-04]
 [-1.72013711e-04]
 [-4.29226916e-05]
 [-1.35153391e-04]
 [ 2.07411005e-04]
 [ 5.88938127e-04]
 [-6.52325169e-05]
 [ 5.48611425e-05]
 [-2.16706955e-04]
 [-4.89365203e-04]
 [-8.02080728e-06]
 [-3.44850014e-04]
 [ 8.34207971e-04]
 [ 1.19570631e-03]
 [ 1.02813861e-04]
 [ 1.74297290e-04]
 [-6.71

ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/miniforge3/conda-bld/yaehmop_1658385592334/work/tightbind/eht_parms.dat using default data in eht_parms.h....
ERROR: Can't open parameter file: /Users/runner/mini

Hii is [[-21.4         -0.          -0.         ...  -0.          -0.
   -0.        ]
 [ -0.         -11.4         -0.         ...  -0.          -0.
   -0.        ]
 [ -0.          -0.         -11.4        ...  -0.          -0.
   -0.        ]
 ...
 [ -0.          -0.          -0.         ... -13.6         -4.15926017
   -3.39214033]
 [ -0.          -0.          -0.         ...  -0.         -13.6
   -3.53140881]
 [ -0.          -0.          -0.         ...  -0.          -0.
  -13.6       ]]
Hij is [[-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -0.00000000e+00 -4.90424120e-07]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -0.00000000e+00 -4.37174107e-07]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -0.00000000e+00 -1.13596192e-07]
 ...
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  -0.00000000e+00 -0.00000000e+00]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00 ... -0.00000000e+00
  

KeyboardInterrupt: 

The `res` object is a namedtuple which contains all the data necessary to perform further analysis.
This object has various attributes which will not be briefly explained.

The `.frames` attribute records which frames from the trajectory were analysed.
This is useful to later cross reference data with the original MD trajectory data.

In [7]:
print(res.frames)

[0 1 2]


The `.degeneracy` attribute stores how many degenerate states were considered for each fragment.
This value will not change over time, so this array has shape `nfragments`.

In this example only a single state per fragment was considered. 

In [8]:
print(res.degeneracy)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


The `.H_frag` attribute contains the molecular coupling values, stored inside a 3d numpy array.
The first dimension is along the number of frames (quasi time axis),
while the other two move along fragments in the system.

For example `res.H_frag[0, 1, 71]` gives the coupling (in eV) between the 2nd and 13th fragments in the first frame.

In [9]:
print(res.H_frag.shape)

print(res.H_frag[2, 1, 71])

(3, 250, 250)
0.0002765886942254432


Producing these results is often a time consuming part of the analysis,
therefore it is wise to save them to a file so you can come back to them later!

This can be done using the `kugupu.save_results` function, which will save the results to a hdf5 (compressed) format.

In [10]:
kgp.save_results('myresults.hdf5', res)

FileExistsError: [Errno 17] Unable to synchronously create file (unable to open file: name = 'myresults.hdf5', errno = 17, error message = 'File exists', flags = 15, o_flags = a02)

These results can then be retrieved again using the `kugupu.load_results` function:

In [ ]:
kgp.load_results('./myresults.hdf5')

KugupuResults(frames=array([0, 1, 2]), H_frag=array([[[-10.27936597,   0.        ,   0.        , ...,   0.        ,
           0.        ,   0.        ],
        [  0.        , -10.32038834,   0.        , ...,   0.        ,
           0.        ,   0.        ],
        [  0.        ,   0.        , -10.35344287, ...,   0.        ,
           0.        ,   0.        ],
        ...,
        [  0.        ,   0.        ,   0.        , ..., -10.43146138,
           0.        ,   0.        ],
        [  0.        ,   0.        ,   0.        , ...,   0.        ,
         -10.50477574,   0.        ],
        [  0.        ,   0.        ,   0.        , ...,   0.        ,
           0.        , -10.37584228]],

       [[-10.38898008,   0.        ,   0.        , ...,   0.        ,
           0.        ,   0.        ],
        [  0.        , -10.43337746,   0.        , ...,   0.        ,
           0.        ,   0.        ],
        [  0.        ,   0.        , -10.44523772, ...,   0.        ,
     